version : "3.5"
services:
  node-app:
    container_name: express-node-app-container
    ports:
      - "4000:4000"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - node-app    
