version : "3"
services:
  node-app:
    build:
        context: .
        target: development
    volumes:
     -  C:\node-app:/app
    environment :  
      - NODE_ENV=development
    command: npm run start-dev     
