version : "3"
services:
  node-app:
    container_name: express-node-app-container
    build: . 
    volumes:
     -  C:\node-app:/app
    ports:
      - "4000:4000"
    env_file:
     - C:\node-app/.env      
